/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const PaymentType = IDL.Variant({
  'money' : IDL.Null,
  'inGameFruits' : IDL.Null,
  'crypto' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'contactInfo' : IDL.Text,
  'paymentMethod' : PaymentType,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'serviceId' : IDL.Nat,
});
export const ServiceCategory = IDL.Variant({
  'discordServices' : IDL.Null,
  'bloxFruits' : IDL.Null,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'acceptedPayments' : IDL.Vec(PaymentType),
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : ServiceCategory,
  'priceUSD' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAvailableServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
  'getService' : IDL.Func([IDL.Nat], [Service], ['query']),
  'getServicesByCategory' : IDL.Func(
      [ServiceCategory],
      [IDL.Vec(Service)],
      ['query'],
    ),
  'submitOrder' : IDL.Func(
      [IDL.Nat, IDL.Nat, PaymentType, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const PaymentType = IDL.Variant({
    'money' : IDL.Null,
    'inGameFruits' : IDL.Null,
    'crypto' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'contactInfo' : IDL.Text,
    'paymentMethod' : PaymentType,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'serviceId' : IDL.Nat,
  });
  const ServiceCategory = IDL.Variant({
    'discordServices' : IDL.Null,
    'bloxFruits' : IDL.Null,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'acceptedPayments' : IDL.Vec(PaymentType),
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : ServiceCategory,
    'priceUSD' : IDL.Float64,
  });
  
  return IDL.Service({
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAvailableServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
    'getService' : IDL.Func([IDL.Nat], [Service], ['query']),
    'getServicesByCategory' : IDL.Func(
        [ServiceCategory],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'submitOrder' : IDL.Func(
        [IDL.Nat, IDL.Nat, PaymentType, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };