/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'contactInfo' : string,
  'paymentMethod' : PaymentType,
  'notes' : string,
  'quantity' : bigint,
  'serviceId' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type PaymentType = { 'money' : null } |
  { 'inGameFruits' : null } |
  { 'crypto' : null };
export interface Service {
  'id' : bigint,
  'name' : string,
  'acceptedPayments' : Array<PaymentType>,
  'description' : string,
  'available' : boolean,
  'category' : ServiceCategory,
  'priceUSD' : number,
}
export type ServiceCategory = { 'discordServices' : null } |
  { 'bloxFruits' : null };
export interface _SERVICE {
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAvailableServices' : ActorMethod<[], Array<Service>>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getService' : ActorMethod<[bigint], Service>,
  'getServicesByCategory' : ActorMethod<[ServiceCategory], Array<Service>>,
  'submitOrder' : ActorMethod<
    [bigint, bigint, PaymentType, string, string],
    bigint
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];