/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Service {
    id: bigint;
    name: string;
    acceptedPayments: Array<PaymentType>;
    description: string;
    available: boolean;
    category: ServiceCategory;
    priceUSD: number;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    contactInfo: string;
    paymentMethod: PaymentType;
    notes: string;
    quantity: bigint;
    serviceId: bigint;
}
export enum OrderStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum PaymentType {
    money = "money",
    inGameFruits = "inGameFruits",
    crypto = "crypto"
}
export enum ServiceCategory {
    discordServices = "discordServices",
    bloxFruits = "bloxFruits"
}
export interface backendInterface {
    getAllOrders(): Promise<Array<Order>>;
    getAllServices(): Promise<Array<Service>>;
    getAvailableServices(): Promise<Array<Service>>;
    getOrder(id: bigint): Promise<Order>;
    getOrdersByStatus(status: OrderStatus): Promise<Array<Order>>;
    getService(id: bigint): Promise<Service>;
    getServicesByCategory(category: ServiceCategory): Promise<Array<Service>>;
    submitOrder(serviceId: bigint, quantity: bigint, paymentMethod: PaymentType, contactInfo: string, notes: string): Promise<bigint>;
    updateOrderStatus(orderId: bigint, newStatus: OrderStatus): Promise<void>;
}
import type { Order as _Order, OrderStatus as _OrderStatus, PaymentType as _PaymentType, Service as _Service, ServiceCategory as _ServiceCategory } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableServices();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableServices();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_Order_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_Order_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByStatus(arg0: OrderStatus): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getService(arg0: bigint): Promise<Service> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_Service_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_Service_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServicesByCategory(arg0: ServiceCategory): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServicesByCategory(to_candid_ServiceCategory_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServicesByCategory(to_candid_ServiceCategory_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitOrder(arg0: bigint, arg1: bigint, arg2: PaymentType, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOrder(arg0, arg1, to_candid_PaymentType_n18(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOrder(arg0, arg1, to_candid_PaymentType_n18(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_OrderStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentType): PaymentType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    acceptedPayments: Array<_PaymentType>;
    description: string;
    available: boolean;
    category: _ServiceCategory;
    priceUSD: number;
}): {
    id: bigint;
    name: string;
    acceptedPayments: Array<PaymentType>;
    description: string;
    available: boolean;
    category: ServiceCategory;
    priceUSD: number;
} {
    return {
        id: value.id,
        name: value.name,
        acceptedPayments: from_candid_vec_n11(_uploadFile, _downloadFile, value.acceptedPayments),
        description: value.description,
        available: value.available,
        category: from_candid_ServiceCategory_n12(_uploadFile, _downloadFile, value.category),
        priceUSD: value.priceUSD
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    contactInfo: string;
    paymentMethod: _PaymentType;
    notes: string;
    quantity: bigint;
    serviceId: bigint;
}): {
    id: bigint;
    status: OrderStatus;
    contactInfo: string;
    paymentMethod: PaymentType;
    notes: string;
    quantity: bigint;
    serviceId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n4(_uploadFile, _downloadFile, value.status),
        contactInfo: value.contactInfo,
        paymentMethod: from_candid_PaymentType_n6(_uploadFile, _downloadFile, value.paymentMethod),
        notes: value.notes,
        quantity: value.quantity,
        serviceId: value.serviceId
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    discordServices: null;
} | {
    bloxFruits: null;
}): ServiceCategory {
    return "discordServices" in value ? ServiceCategory.discordServices : "bloxFruits" in value ? ServiceCategory.bloxFruits : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): OrderStatus {
    return "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : "inProgress" in value ? OrderStatus.inProgress : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    money: null;
} | {
    inGameFruits: null;
} | {
    crypto: null;
}): PaymentType {
    return "money" in value ? PaymentType.money : "inGameFruits" in value ? PaymentType.inGameFruits : "crypto" in value ? PaymentType.crypto : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentType>): Array<PaymentType> {
    return value.map((x)=>from_candid_PaymentType_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n9(_uploadFile, _downloadFile, x));
}
function to_candid_OrderStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentType): _PaymentType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): _ServiceCategory {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): {
    discordServices: null;
} | {
    bloxFruits: null;
} {
    return value == ServiceCategory.discordServices ? {
        discordServices: null
    } : value == ServiceCategory.bloxFruits ? {
        bloxFruits: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentType): {
    money: null;
} | {
    inGameFruits: null;
} | {
    crypto: null;
} {
    return value == PaymentType.money ? {
        money: null
    } : value == PaymentType.inGameFruits ? {
        inGameFruits: null
    } : value == PaymentType.crypto ? {
        crypto: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
